In [6]:
import pandas as pd
import numpy as np

In [9]:
ny_data = pd.read_csv("2017.csv")
ny_data

,LicenseType,Breed,Color,DogName,OwnerZip,ExpYear,ValidDate
0,Dog Individual Spayed Female,BICHON FRISE,WHITE,CHLOE,15090,2017,12/15/2016 9:58
1,Dog Senior Citizen or Disability Spayed Female,CHIHUAHUA,WHITE/BLACK/BROWN,CHALUPA,15120,2017,3/23/2017 14:32
2,Dog Individual Spayed Female,LAB MIX,YELLOW,MIA,15133,2017,2/28/2017 10:59
3,Dog Individual Male,DACHSHUND,BLACK/BROWN/GREY,CODY,15108,2017,2/9/2017 13:40
4,Dog Individual Spayed Female,DACHSHUND,BLACK,SOPHIE,15108,2017,2/9/2017 13:40
...,...,...,...,...,...,...,...
21722,Dog Individual Female,BOXER,BRINDLE,RUBY,15116,2017,3/27/2017 14:47
21723,Dog Individual Spayed Female,MIXED,WHITE/BLACK,STELLALUNA,15216,2017,3/27/2017 14:53
21724,Dog Individual Male,LABRADOR RETRIEVER,BLACK,JAXXON,15112,2017,3/27/2017 14:53
21725,Dog Individual Female,GER SHEPHERD,BLACK/TAN,BONNIE,15202,2017,3/28/2017 8:45
21726,Dog Senior Citizen or Disability Neutered Male,CHIHUAHUA,BLACK,DOZER,15210,2017,3/28/2017 8:45